services:
  - type: web
    name: zomato-opspro-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8082
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: zomato-opspro-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: zomato-opspro-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: zomato-opspro-db
          property: password

  - type: web
    name: zomato-opspro-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://zomato-opspro-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: zomato-opspro-db
    databaseName: opspro
    plan: free 